### ISSUE TITLE
White Screen - home screen and dialog boxes

### ISSUE THREAD

**Issue by gtwaites** [bambulab/BambuStudio#1201]
BambuStudio was running perfectly until Windows 11 upgrade. Now home screen is blank (see attached) and dialog boxes are blank.

Configuration:
Intel Core i7-9700
32GB RAM
Windows 11 Pro, Build 22000.1516
Nvidia GeForce RTX 2060, Driver: 528.24
BambuStudio v01.04.02.13

![Bambu AMS Dialog Box](https://user-images.githubusercontent.com/35669055/215289597-c8c10d91-0b9a-4e43-985e-69e8ccb780d3.jpg)
![Bambu Home Screen](https://user-images.githubusercontent.com/35669055/215289598-8d26b92d-d19f-4310-bffa-257934016c06.jpg)

**Comment by SaltWei** [comment]
@gtwaites 
Could you zip all the log files in C:\Users\user.name\AppData\Roaming\BambuStudio\log and upload here?

we will have a check. Thank you very much!

**Comment by StoneLiBambulab** [comment]
Fixed and the next version is coming soon.


Thanks!
Stone Li

**Comment by SaltWei** [comment]
Available in v1.5.0 Public Beta

**Comment by Drilmo** [comment]
Hi, 
I'm on last version and i have same error, i can't login...
![image](https://user-images.githubusercontent.com/31286436/235485351-b0762672-4919-4c40-9fa6-0cf4c34d845d.png)

**Comment by chapterv** [comment]
![login](https://github.com/bambulab/BambuStudio/assets/5164109/9d4fca11-af02-462b-864a-188aa2c44bac)
not fixed

**Comment by Helton-Loureiro** [comment]
I have the same problem
![image](https://github.com/bambulab/BambuStudio/assets/90007509/ae01d503-3251-4ee5-a798-d9cce459abfb)
