### ISSUE TITLE
Linux Wayland support 

### ISSUE THREAD

**Issue by officiallymarky** [bambulab/BambuStudio#2595]
I am using the App Image for Linux but it runs in xwayland mode (Wayland compatibility) which runs really poorly. 

Most Linux apps using electron can forced into Wayland mode eliminating the graphic and performance glitches but I can’t find anyway to force BS to use Wayland.  

Linux distributions are moving away from X11 and only supporting Wayland going forward (Fedora just recently proposed this).

**Comment by xux1217** [comment]
yeah, we need wayland support directly, please add it, thanks~

**Comment by hadess** [comment]
This would at least need:
- removing the `GDK_BACKEND` setting in `src/BambuStudio.cpp`
- making sure to enable Wayland support in GLFW, glew and wxWidgets

**Comment by Botspot** [comment]
This is especially necessary on low-power computing platforms such as the Raspberry Pi, which now use Wayland.
Any 3D panning that is rendered through xWayland can be expected to have a low frame rate and keep the CPU occupied at 100% utilization.

I'm interested in adding BS to [our ARM app store](https://github.com/Botspot/pi-apps), alongside Cura, PrusaSlicer, and other slicers. But it needs to be usable. Maybe it is usable on xwayland, but it would be a lot more usable if wayland could be enabled.

**Comment by different-name** [comment]
The prepare and preview windows do not appear on Wayland for me

Hyprland, built from branch v0.44.1-b at commit 4520b30d498daca8079365bdb909a8dea38e8d55

![image](https://github.com/user-attachments/assets/c1a93e63-61a8-40b1-8cac-cb4947ebe733)

**Comment by officiallymarky** [comment]
> The prepare and preview windows do not appear on Wayland for me
> 
> Running through xwayland, Hyprland, built from branch v0.44.1-b at commit 4520b30d498daca8079365bdb909a8dea38e8d55
> 
> ![image](https://private-user-images.githubusercontent.com/49257026/382491910-c1a93e63-61a8-40b1-8cac-cb4947ebe733.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1ODMzNTQsIm5iZiI6MTczMDU4MzA1NCwicGF0aCI6Ii80OTI1NzAyNi8zODI0OTE5MTAtYzFhOTNlNjMtNjFhOC00MGIxLThjYWMtY2I0OTQ3ZWJlNzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDIxMzA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MTYyYjdlY2FiZWQ2YTI0M2Y3ODAxMzAwMmZjNGY4ZWZlYTg5ZjJmN2RmNDM0ZGZlZmYwYzcwNTRjZDVlNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dMYZ7xDYevoJvk4qHr9ItVW1hbg5zEZzuAyuSClK1tA)

Give this a try

WEBKIT_DISABLE_DMABUF_RENDERER=1

**Comment by different-name** [comment]
> Give this a try
> 
> WEBKIT_DISABLE_DMABUF_RENDERER=1

Ran `WEBKIT_DISABLE_DMABUF_RENDERER=1 bambu-studio` with no change

**Comment by mordicuac** [comment]
Same issue here with an Nvidia 2060

**Comment by different-name** [comment]
> The prepare and preview windows do not appear on Wayland for me

> Same issue here with an Nvidia 2060

There's an issue open for the lacking 3D view on Wayland with Nvidia 560 and 565 drivers

https://github.com/bambulab/BambuStudio/issues/4669#issuecomment-2309647796

Downgrading to 555.58.02 resolved the issue for me, hopefully will be fixed in a later revision of the Nvidia drivers or Bambu Studio

**Comment by jonofmac** [comment]
Here we are in 2025 with this issue still here lol. Guess we aren't considering this a bug??

**Comment by eternal-sorrow** [comment]
>Guess we aren't considering this a bug??

It's not a bug, it's a feature request.

**Comment by officiallymarky** [comment]
> > Guess we aren't considering this a bug??
> 
> It's not a bug, it's a feature request.

Supporting the most popular and the primary display server going forward isn't a feature request, it's necessary.

**Comment by eternal-sorrow** [comment]
While I agree that native Wayland support would be nice to have, it's hardly necessary because X11 software seamlessly works on Wayland thanks to Xwayland.

**Comment by officiallymarky** [comment]
> While I agree that native Wayland support would be nice to have, it's hardly necessary because X11 software seamlessly works on Wayland thanks to Xwayland.

While I'd like to agree, Bambu Slicer has issues w/ Wayland.

**Comment by eternal-sorrow** [comment]
>Bambu Slicer has issues w/ Wayland

Even then, those issues could be fixed without porting the whole thing to Wayland (and probably introducing more issues along the way). In any case, this doesn't make the missing Wayland support a bug (unless the developers would consider it so).

That being said, I personally would still love to see the Wayland support added, maybe behind some kind of a switch at first for the volunteers to test and report issues back.

**Comment by Alextibtab** [comment]
Just a potential temporary fix for anyone having issues, `__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json WEBKIT_FORCE_COMPOSITING_MODE=1 WEBKIT_DISABLE_COMPOSITING_MODE=1 WEBKIT_DISABLE_DMABUF_RENDERER=1 bambu-studio` thanks to @lkarlslund for a similar issue with orcaslicer. This lets me see the 3D preview it's a bit laggy but better than nothing at all.

**Comment by officiallymarky** [comment]
> Just a potential temporary fix for anyone having issues, `__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json WEBKIT_FORCE_COMPOSITING_MODE=1 WEBKIT_DISABLE_COMPOSITING_MODE=1 WEBKIT_DISABLE_DMABUF_RENDERER=1 bambu-studio` thanks to [@lkarlslund](https://github.com/lkarlslund) for a similar issue with orcaslicer. This lets me see the 3D preview it's a bit laggy but better than nothing at all.

I have really poor performance with Orca Slicer, most of the time I can get in slice and print fast enough before it is really an issue, it was really bad with Bambu Slicer, but latest versions I couldn't even get to work with Linux due to it not displaying the panels even with env vars and other tweaks.  The performance is atrocious and unusable for anything but changing a few settings and hitting slice and print.

**Comment by notFunnys** [comment]
> Just a potential temporary fix for anyone having issues, `__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json WEBKIT_FORCE_COMPOSITING_MODE=1 WEBKIT_DISABLE_COMPOSITING_MODE=1 WEBKIT_DISABLE_DMABUF_RENDERER=1 bambu-studio` thanks to [@lkarlslund](https://github.com/lkarlslund) for a similar issue with orcaslicer. This lets me see the 3D preview it's a bit laggy but better than nothing at all.

Thanks man, that works great. I replaced the exec command in the bambu-studio.desktop file with the commands. i don't even have any laggs, it's just as smooth as in the windows app

**Comment by officiallymarky** [comment]
> > Just a potential temporary fix for anyone having issues, `__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json WEBKIT_FORCE_COMPOSITING_MODE=1 WEBKIT_DISABLE_COMPOSITING_MODE=1 WEBKIT_DISABLE_DMABUF_RENDERER=1 bambu-studio` thanks to [@lkarlslund](https://github.com/lkarlslund) for a similar issue with orcaslicer. This lets me see the 3D preview it's a bit laggy but better than nothing at all.
> 
> Thanks man, that works great. I replaced the exec command in the bambu-studio.desktop file with the commands. i don't even have any laggs, it's just as smooth as in the windows app

The only one you really need is this:

`__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json `

**Comment by jonofmac** [comment]
> > > Just a potential temporary fix for anyone having issues, `__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json WEBKIT_FORCE_COMPOSITING_MODE=1 WEBKIT_DISABLE_COMPOSITING_MODE=1 WEBKIT_DISABLE_DMABUF_RENDERER=1 bambu-studio` thanks to [@lkarlslund](https://github.com/lkarlslund) for a similar issue with orcaslicer. This lets me see the 3D preview it's a bit laggy but better than nothing at all.
> > 
> > 
> > Thanks man, that works great. I replaced the exec command in the bambu-studio.desktop file with the commands. i don't even have any laggs, it's just as smooth as in the windows app
> 
> The only one you really need is this:
> 
> `__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json `

Can confirm. Adding only this line to the bambulabs studio launcher environmental variables worked

1) Open application menu, search for bambustudio, right click, properties
2) Application, enter environmental variables

![Image](https://github.com/user-attachments/assets/423913bb-985d-4c95-8d9a-a36df816d55c)

**Comment by EmilyNerdGirl** [comment]
> > > > Just a potential temporary fix for anyone having issues, `__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json WEBKIT_FORCE_COMPOSITING_MODE=1 WEBKIT_DISABLE_COMPOSITING_MODE=1 WEBKIT_DISABLE_DMABUF_RENDERER=1 bambu-studio` thanks to [@lkarlslund](https://github.com/lkarlslund) for a similar issue with orcaslicer. This lets me see the 3D preview it's a bit laggy but better than nothing at all.
> > > 
> > > 
> > > Thanks man, that works great. I replaced the exec command in the bambu-studio.desktop file with the commands. i don't even have any laggs, it's just as smooth as in the windows app
> > 
> > 
> > The only one you really need is this:
> > `__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json `
> 
> Can confirm. Adding only this line to the bambulabs studio launcher environmental variables worked
> 
> 1. Open application menu, search for bambustudio, right click, properties
> 2. Application, enter environmental variables
> 
> ![Image](https://github.com/user-attachments/assets/423913bb-985d-4c95-8d9a-a36df816d55c)

Thank you! This works great with AppImages too on Ubuntu

**Comment by snoack** [comment]
Interestingly for me setting `__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json` makes things worse. If I set this env var, the home tab remains blank as well, without it only the 3D view in prepare + preview is blank.

This issue just recently started for me, Bambu Studio just worked fine a couple days ago, not exactly sure what changed, maybe some package updates. I'm using the Flatpak version. The issue persists regardless whether I use Wayland or Xorg.

I previously had other rendering issues in Bambu Studio on a different laptop with Nvidia graphics when using fractional scaling. But my current laptop has only Intel integrated graphics.

**Comment by zish** [comment]
> 
> Give this a try
> 
> WEBKIT_DISABLE_DMABUF_RENDERER=1

This seems to have fixed things for me. My fonts seem to be rendered correctly now.

**Comment by mzhaase** [comment]
I want to bring this up again since starting from Ubuntu 25.10, GNOME does not run with X11 anymore. As a result, bambu studio does not work for me on 25.10, and will also not run on the next Ubuntu LTS version.

**Comment by mzhaase** [comment]
Just as a datapoint, the current release, Bambu_Studio_ubuntu-24.04_PR-8834.AppImage works on 25.10

**Comment by eternal-sorrow** [comment]
>Just as a datapoint, the current release, Bambu_Studio_ubuntu-24.04_PR-8834.AppImage works on 25.10

Even if Ubuntu doesn't ship X11 session anymore, it doesn't mean it can't run X11 apps. Xwayland exists for that specific task.

Existence of Xwayland is not a reason to not port apps to Wayland natively though.

**Comment by CloudCassette** [comment]
Confirming similar performance symptoms on the Flatpak build.

## Summary
- Shortly after launch, the UI becomes very sluggish (menus, viewport interactions, general window responsiveness), consistent with the behavior described in this issue.
- I suspect Wayland may be a factor.

## Environment
- App ID: com.bambulab.BambuStudio
- Version: 2.4.0 Public Release (Flathub stable)
- Runtime: org.gnome.Platform/x86_64/48
- Flatpak: 1.16.1
- OS: Fedora Linux
- GNOME Shell: 49.2
- Session: Wayland
- Architecture: x86_64
- OpenGL: Mesa Intel(R) Graphics (RPL-U), Mesa 25.2.7 (GL 4.6 core)

## Notes
- Session is Wayland; I can retest under X11/XWayland if helpful (e.g., via QT_QPA_PLATFORM=xcb). Logs for both default (Wayland) and XCB runs are attached.
- Happy to provide longer captures or additional traces (perf/sysprof) if needed.

## Command used for X11/XWayland retest
```bash
flatpak run --env=QT_QPA_PLATFORM=xcb com.bambulab.BambuStudio
```

## Context from this thread
- Read through prior comments: several participants note Bambu Studio runs under XWayland on Wayland sessions and request native Wayland support due to glitches and performance issues.
- Reports include repeated GTK module warnings, Gtk-CRITICAL size/allocation assertions, and messages like “Cannot register URI scheme wxfs/memory more than once.” My logs show the same patterns.
- I’m attaching structured logs and exact environment details to help triage; happy to provide longer captures or profiling if useful.

## Sandbox windowing variables
Default environment observed inside the Flatpak sandbox:
```
WAYLAND_DISPLAY=wayland-0
DISPLAY=:0
GDK_BACKEND=
QT_QPA_PLATFORM=
```

## Questions for maintainers
- Should I prioritize reproductions on Wayland, XWayland (GDK_BACKEND=x11), or both?
- Is Bambu Studio expected to run natively on Wayland with wxGTK, or via XWayland? If native, which wx/GTK versions are required for support?
- Any preferred debug env vars to capture next time? Examples: G_MESSAGES_DEBUG=all, GDK_DEBUG=gl-egl, LIBGL_DEBUG=verbose, MESA_DEBUG=1, WXTRACE=all.
- Would an apitrace/sysprof capture help, and if so, which area should I focus on (windowing events vs OpenGL rendering)?
- Do you want a comparison run with the upstream AppImage to separate Flatpak packaging from application issues?
- Any GNOME settings worth toggling for repros (e.g., fractional scaling, triple buffering)?
- Should I try software rendering as a control (LIBGL_ALWAYS_SOFTWARE=1) and attach that log?
- Would xdg-desktop-portal logs be useful; if yes, which portal(s) should I enable debug for?


## Attachments
- bambu-logs-redacted.tar.gz (contains:
  - bambu-studio-default.log — default Wayland run (~60s)
  - bambu-studio-xcb.log — XCB (X11) run (~60s)
  - glxinfo.txt, flatpak-info.txt, flatpak-version.txt, permissions.txt, host-env.txt, sandbox-env.txt
  - Private/loopback IPs redacted)


[bambu-logs-redacted.tar.gz](https://github.com/user-attachments/files/24118262/bambu-logs-redacted.tar.gz)

**Comment by avicarpio** [comment]
Please fix this

**Comment by stsquad** [comment]
Have you tried building from source? Generally all the Wayland specifics should be handled by the toolkit so building against your own system libs instead of whatever is in the flatpak should work.

**Comment by eternal-sorrow** [comment]
Bambu studio bundles it's own patched version of WxWidgets.

**Comment by stsquad** [comment]
It looks like the Bambu version forked before wxWidgets Wayland support (3.1.5 vs 3.2.0) but the cherry doesn't look too scary:

```
➜  git cherry -v 9c0a8be1dc32063d91ed1901fd5fcd54f4f955a1 bambu/master
+ 9823ecab953d2a16c1d393728bc9f2272e366cf1 Fix for BambuStudio
+ 761ba5f7cb644afa194d4f61a84ab48fb8df2a22 Set to wx-expected clipping behavior of drawRect
+ a8e20d055327d52c4037f3d23efe2412c88a1a94 Work around MSVS 2022 optimizer bug in wxImage::ShrinkBy()
+ 63af1d69186eec26ccb2b6949dca96107d3aff4e Add support for building WebView with libwebkit2gtk-4.1
+ 66a0ce3c438e1807a14bf5065a8606557d3193c7 FIX: disable gstplayer https://github.com/bambulab/BambuStudio/issues/3279
+ d97effea143f661ee5ee765c9dd31f77cb7a4e2b ENH: build: set WEBVIEW2_ARCH to arm64 for windows arm64
+ 8fd6f8c580217ddebfea404b823c71e203d83055 Support SetUserDataPathOption in wxWebViewEdge
```

plus the patch in BambuStudio.git/deps/wxWidgets/0001-wxWidget-fix.patch

I wonder how many of those patches are needed against the current wxWidgets?

**Comment by hadess** [comment]
> It looks like the Bambu version forked before wxWidgets Wayland support (3.1.5 vs 3.2.0) but the cherry doesn't look too scary:

It's been using "git master" instead of a versioned release for about 6 months:
https://github.com/bambulab/BambuStudio/commit/a181250668fae3110e329c0dd289f1e71dd1bb45

So there's no patches to wxWidgets anymore.

**Comment by eternal-sorrow** [comment]
But does it build it with Wayland support?

**Comment by stsquad** [comment]
That should come in automatically with GTK3, although I noticed the build has:

```
set(_wx_egl "-DwxUSE_GLCANVAS_EGL=OFF")
```

which might get in the way.

**Comment by dblueman** [comment]
> Have you tried building from source? Generally all the Wayland specifics should be handled by the toolkit so building against your own system libs instead of whatever is in the flatpak should work.

There are build issues when using local dependencies; I have fixed the ones I found on Ubuntu 25.10 on ARM64 (Snapdragon X1) at https://github.com/bambulab/BambuStudio/pull/9252

**Comment by dblueman** [comment]
I find frequent "BambuStudio Is Not Responding" UI modal dialogues and multi-minute hangs making release 2.4.0 unusable on Ubuntu 25.10 on x86-64.

Since everyone needing to run Ubuntu 22.04 LTS now runs Ubuntu 24.04 LTS, the former should already be removed and Bambu Lab should focus effort on Ubuntu 26.04 LTS, just weeks away to avoid user base attrition.

**Comment by mariobaldini** [comment]
I'm facing the issue with `Bambu_Studio_linux_fedora-v02.04.00.70.AppImage` (or flatpak) on Fedora 43. 

Tried several workarounds suggested in the past, that doesn't seem to work now. 

Is there any workaround to make it work right now? 
App starts, but windows randomly freezes and is basically unusable. 


Right now for me the most usable is installing the flatpak version and
`flatpak run --env=WEBKIT_DISABLE_DMABUF_RENDERER=1 com.bambulab.BambuStudio`

**Comment by phisch** [comment]
I have tried to find any workaround or getting it to work as a native wayland client, but didn't find anything that improves the current situation. Bambu Studio is borderline unusable on wayland. Surfaces turn black for 3-10 seconds, the app has constant freezes for 5-infinite seconds (you gotta force quit it if it doesn't recover), it often crashes while trying to go to the device tab or sending a print.

This is a QT app, and QT can run natively on wayland. I would like to know what stops Bambu Studio from working like all other QT apps?

**Comment by Semt3x** [comment]
I find it crazy that this is still an issue...
And I can't even switch to Orca (that has it a bit better despite being a fork) as it doesn't support my H2D....

**Comment by wolfallein** [comment]
Just got the P1S printer and cannot use the Bambu Studio due to scaling issues on Wayland. I cannot click on buttons, texts are missing...
 I hope this gets fixed soon, but this issue is open since 2023.
I'll probably return this printer because I cannot slice anything.

**Comment by avicarpio** [comment]
@wolfallein Same for me, I cannot use my Bambulab A1

**Comment by stsquad** [comment]
I'm running the AppImage (Bambu_Studio_ubuntu-24.04_PR-8834.AppImage) under Wayland without issues. I guess that comes from a PR build though. The flatpak image is still broken for Wayland and I still struggle to build from source on my Debian system.

**Comment by avicarpio** [comment]
@stsquad I just tested Bambu_Studio_ubuntu-24.04_PR-8834.AppImage and it doesn't work either on Fedora 43, Wayland, Intel, Nvidia driver 580.

**Comment by avicarpio** [comment]
@stsquad Man, thanks for your comment! It gave me the idea to look for an AppImage that just works, and I found one! Not for BambuStudio, but for OrcaSlicer, I can use my printer now! For other users who have the same problem, this is the AppImage I found that works. Download the Ubuntu version from the artifacts below (@wolfallein , @Semt3x , @phisch , @mariobaldini , @dblueman):
https://github.com/OrcaSlicer/OrcaSlicer/actions/runs/21644455787?pr=12119

**Comment by phisch** [comment]
@avicarpio I had to give this a test, since it sounds great, and it did seem a bit faster initially, but after it was setup, and I restarted it, it went back to being painfully slow.

Just for clarity:
- I uninstalled all instances of bambu studio and orca slicer
- downloaded the `OrcaSlicer-Linux-flatpak_PR-12119_x86_64.flatpak` from the [build you linked](https://github.com/OrcaSlicer/OrcaSlicer/actions/runs/21644455787?pr=12119)
- ran `flatpak install OrcaSlicer-Linux-flatpak_PR-12119_x86_64.flatpak`

You really had my hopes up ^^

**Comment by avicarpio** [comment]
> @avicarpio I had to give this a test, since it sounds great, and it did seem a bit faster initially, but after it was setup, and I restarted it, it went back to being painfully slow.
> 
> Just for clarity:
> - I uninstalled all instances of bambu studio and orca slicer
> - downloaded the `OrcaSlicer-Linux-flatpak_PR-12119_x86_64.flatpak` from the [build you linked](https://github.com/OrcaSlicer/OrcaSlicer/actions/runs/21644455787?pr=12119)
> - ran `flatpak install OrcaSlicer-Linux-flatpak_PR-12119_x86_64.flatpak`
> 
> You really had my hopes up ^^

Not flatpak, try AppImage

**Comment by dmitrii-galantsev** [comment]
hey just FYI - it uses XWayland under the hood still

**Comment by phisch** [comment]
@avicarpio I don't think there is an AppImage in the build you linked. Am I blind?

> hey just FYI - it uses XWayland under the hood still

That's to be expected, but any performance improvement is desperately needed!

**Comment by avicarpio** [comment]
@phisch I can't paste the download link but yes, it is. Download "OrcaSlicer_Linux_ubuntu_2404_PR-12119" and you will find an AppImage inside a .zip

**Comment by phisch** [comment]
Ah, that's where it was! I'm glad it works better for you, but even the appimage is just as slow as all the other installs for me.

**Comment by dmitrii-galantsev** [comment]
I believe the issue is with outdated wxwidgets.
https://github.com/bambulab/wxWidgets

It's quite a bit of work to update it. Maybe we can cherry-pick some patch that clearly fixes the issue like we do in https://github.com/SoftFever/Orca-deps-wxWidgets/pull/5

**Comment by SR-G** [comment]
Same problem here.
With GNOME 50 (and Wayland activated automatically at update time), at first, Bambu Studio was not working anymore at all.
At some point (under Archlinux / non-LTS), it somehow started to work again.
Recently, it's not working anymore again = on my side, the app is starting, but there is nothing displayed in the 3D panel under Prepare / Preview tabs (just a blank area).
At some point i get some crashes / segmentation fault, sometimes.

```
use_count = 4
double free or corruption (out)
corrupted double-linked list
[1]    3588630 IOT instruction (core dumped)  GSK_RENDERER=cairo GDK_BACKEND=x11 
```

I tried many of these parameters (GSK_RENDERER configured or not, GDK_BACKEND configured or not, etc.), but it's (now) always the same behavior.

(note / extra rant : i just hate wayland - it does not bring anything at all, and it generates so many issues everywhere)

**Comment by ErroneousBosch** [comment]
Wayland is trash, but moving forward more and more distros are shifting to it to be "more modern". Oddly, on EndeavourOS (Arch spin), my AMD APU laptop has way fewer issues than my NVidia dGPU desktop.

**Comment by Semt3x** [comment]
Not having issues with Nvidia would be the odd thing.
I spent 1 day reinstalling Arch / Fedora last week because the newer version of the kernels need new flags

Yoann MENELET

-------- Original Message --------

**Comment by ErroneousBosch** [comment]
@Semt3x Fair. Seriously considering whether I want to keep my 5060 TI or sell it and pickup a 9060XT

**Comment by jm355** [comment]
Bambu studio flatpak does not open at all. I do not have xwayland.

**Comment by mindrunner** [comment]
Started working on this in https://github.com/bambulab/BambuStudio/pull/11821. Native Wayland mostly works now (opt-in via GDK_BACKEND=wayland, default behavior unchanged), but the 3D viewport still goes blank after loading a model in some configurations. Only tested on Arch + Hyprland with Intel and NVIDIA so far. Testers on other distros/compositors/GPUs would help a lot, and so would anyone who knows the GL/EGL side better than I do.
