### ISSUE TITLE
Font change not working anymore

### ISSUE THREAD

**Issue by ntreimers-beep** [bambulab/BambuStudio#8325]
### Bambu Studio Version

2.2.2.56

### Where is the application from?

Bambu Lab Official website

### OS version

OS: Windows 10 & Windows 11 (two different machines)

### Printer

BambuLab A1 (this is not involved though, the problem is in Bambu Studio)

### How to reproduce

Make text using `Bahnschrift` font and another text using `Bahnschrift Light Condensed`, notice that they look exactly the same. 

I'm not sure when this was broken, but it used to work correctly with a previous version of Bambu Studio.

### Actual results

Here is a screenshot side by side with MS Word where you can see the difference between the fonts:
<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/e5036f33-a4e0-4e21-a9b7-dbdbb3ef720e" />

### Expected results

Choosing a different font variant will show the changes properly.

### Project file & Debug log uploads

[FontIssue.zip](https://github.com/user-attachments/files/22624532/FontIssue.zip)

[logs.zip](https://github.com/user-attachments/files/22624574/logs.zip)

### Checklist of files to include

- [x] Log file
- [x] Project file

**Comment by ntreimers-beep** [comment]
I confirmed that downgrading to version v02.01.01.52 of Bambu Studio does not show this problem.

**Comment by Haidiye00** [comment]
Hello, I'm very sorry, this is a known issue and we are still analyzing and resolving it~

**Comment by cecchet** [comment]
It used to work for me on 2.2.1.60 (though the Helio Additive Optimization never showed up in the options after the upgrade from 2.0). But since the 2.3.0 update the text functionality is broken (mine defaults to Arial whatever font I put in) and it fails to modify existing text as well (it crashed randomly before but now it's just 100% broken). As a note, v 2.3.0 finally installed Helio, not sure if it's related or not.

**Comment by cecchet** [comment]
Note that the font change works in the Dialog box itself when editing the text but it does not apply the font to the model.
Downgrading to 2.2.2.56 temporarily fixed the issue.

**Comment by jbast1224** [comment]
Text has been catastropically broken since the function evolution. Downgrading to 2.01.01.52 does in fact return the old functionality. this update has completely lost different font weights (bold, semibold, extra bold, etc.), and 2.3.0 reverts fonts to arial and occasionally crashes the application while editing text.

**Comment by LittleMountainMaps** [comment]
Totally agree with jbast1224. I have had to revert to 2.01.01.52 repeatedly because the text tool is unusable for me in every subsequent version. In particular, the Bahnschrift family of fonts all display identically; there is no variation in width or weight regardless of which font is selected. I am hoping this is addressed soon so I can take advantage of other updates introduced in newer versions.

**Comment by jbast1224** [comment]
> Totally agree with jbast1224. I have had to revert to 2.01.01.52 repeatedly because the text tool is unusable for me in every subsequent version. In particular, the Bahnschrift family of fonts all display identically; there is no variation in width or weight regardless of which font is selected. I am hoping this is addressed soon so I can take advantage of other updates introduced in newer versions.

Orbitron as well. All of them appear the same on the model, and in the font selection dropdown.

**Comment by LittleMountainMaps** [comment]
This issue is still present in the latest version 2.4.0.70.

**Comment by LittleMountainMaps** [comment]
This issue is still present in the latest version 2.5.3.61.

**Comment by pgifford** [comment]
Still present in v2.7.1.62, all weights of Work Sans look the same (Windows 11).  Note that I'd installed the variable weight versions of the font; see my next message for more on that.

**Comment by pgifford** [comment]
Bambu Studio cannot handle variable weight fonts but does just fine with static versions of the same font.  I download Work Sans from Google Fonts to use on some labels.  Here's what I found:

### Does not work
* `WorkSans-VariableFont_wght.ttf`
* `WorkSans-Italic-VariableFont_wght.ttf`

### Works
Every font in the `static` directory (font comes as a zip file, this is a partial listing):
* `WorkSans-Black.ttf`
* `WorkSans-BlackItalic.ttf`
* `WorkSans-Regular.ttf`
* `WorkSans-SemiBold.ttf`
* `WorkSans-SemiBoldItalic.ttf`
