### ISSUE TITLE
App crashes after sent print job to printer

### ISSUE THREAD

**Issue by tom5677** [bambulab/BambuStudio#8507]
### Bambu Studio Version

2.3.0.70

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

BambuLab P1S

### Printer Firmware Version

01.09.00.00

### How to reproduce

Slice model
Send to printer for print
window for sendig is still open
seems wen switching to status window (with camera) it crashes

### Actual results

app crashes

### Expected results

app should not crash but show the status window/tab

### Project file & Debug log uploads

[log.zip](https://github.com/user-attachments/files/23055562/log.zip)

### Checklist of files to include

- [x] Log file
- [ ] Project file

**Comment by BoBoYu-BamBu** [comment]
@tom5677 Thank you for your feedback. Could you please delete the configuration file and try again? We have already fixed this issue internally. Please wait for the next version.

**Comment by tom5677** [comment]
> [@tom5677](https://github.com/tom5677) Thank you for your feedback. Could you please delete the configuration file and try again? We have already fixed this issue internally. Please wait for the next version.

@BoBoYu-BamBu thank you for your quick response. How can I delete "the configuration file"? Where is it located and what's the name? Thx,Tom

**Comment by BoBoYu-BamBu** [comment]
> > [@tom5677](https://github.com/tom5677)感谢您的反馈。请问您能否删除配置文件并重试？我们已经在内部修复了这个问题。请等待下一个版本。
> 
> [@BoBoYu-BamBu](https://github.com/BoBoYu-BamBu)感谢您的快速回复。我该如何删除“配置文件”？它位于哪里？名字是什么？谢谢，汤姆

@tom5677 Thank you for your feedback. It might be that there is a problem with the configuration file. Could you please delete it and try again? If you have any further questions, please let us know.
<img width="654" height="415" alt="Image" src="https://github.com/user-attachments/assets/d3752c22-6a45-481e-9c65-18acb561208a" />
<img width="1077" height="331" alt="Image" src="https://github.com/user-attachments/assets/4ac404a1-3006-4bc2-ba4a-5ce63f27a99c" />

**Comment by tom5677** [comment]
Hey @BoBoYu-BamBu , unfortunately it didn's work. I've configured averything from start. Still crash after send to printer (via cloud) was completed

**Comment by BoBoYu-BamBu** [comment]
Sorry，We have already fixed this issue internally. Please wait for the next version.

**Comment by tom5677** [comment]
OK, Thanks. Just FYI: I've realized that the crash happend when I close the "send print job" window - even without sending the pint job via "send" button.

**Comment by tom5677** [comment]
Fixed in 2.3.1.51. https://github.com/bambulab/BambuStudio/releases/tag/v02.03.01.51
