### ISSUE TITLE
[*Issue*] BS 1.4.0.17 Failed to Get Network Plugin

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#852]
Everything was working OK untill I updated to version 1.4.0.17.
Bambu Studio can't get network plugin and I can't access to my printer from BS now.
Nothing has changed on my PC, BS was working well yesterday. Using W7.
Tried to do a clean install, deleted user data, disabling antivirus, firewalls, etc. Nothing seems to work.

**Comment by lanewei120** [comment]
the network plugins have been updated to new servers with cdn
there is a known issue that windows 7/8 can not download it by using SChannel in curl

we are trying to switch to use openssl instead
and if it is doable, we will release a hotfix version.

currently you can download if from https://public-cdn.bambulab.com/upgrade/studio/plugins/01.04.00.15/win_01.04.00.15.zip
and extract them into C:\Users\user.name\AppData\Roaming\BambuStudio\plugins manually

sorry for this inconvinience

**Comment by lanewei120** [comment]
already fixed in v1.4.2

**Comment by bjornsyse** [comment]
I have this problem now again from 1.05. Where can I find the plugin manually? 

I cannot access my printer anymore.,

**Comment by lanewei120** [comment]
> I have this problem now again from 1.05. Where can I find the plugin manually?
> 
> I cannot access my printer anymore.,

do you mean it worked in previous version?
what is your OS using?
and could you send the log in C:\Users\user.name\AppData\Roaming\BambuStudio\log for us to check

it maybe a different issue, most likely network related.
anyway, you can download it from 
https://public-cdn.bambulab.com/upgrade/studio/plugins/01.05.00.10/win_01.05.00.10.zip for windows

**Comment by bjornsyse** [comment]
I'm on windows 10. I found the file manually in the log file but even after placing the file in plugins folder I still can't get around the error msg when launch the software. 

Log file  attached

**Comment by bjornsyse** [comment]
Are there any domains changed for cdn's since last time? I've had to whitelist them with my proxy provider the last time.

**Comment by lanewei120** [comment]
> 

still can not find the log files
it should be something wrong...

**Comment by bjornsyse** [comment]
[debug_Mon_Mar_13_08_23_44_10160.log.zip](https://github.com/bambulab/BambuStudio/files/10954841/debug_Mon_Mar_13_08_23_44_10160.log.zip)
Sorry, log file was refued because of file extension, I zipped it now.

**Comment by lanewei120** [comment]
> [debug_Mon_Mar_13_08_23_44_10160.log.zip](https://github.com/bambulab/BambuStudio/files/10954841/debug_Mon_Mar_13_08_23_44_10160.log.zip) Sorry, log file was refused because of file extension, I zipped it now.

2023-03-13 08:23:49.368140[Thread 0x000096f4]:[install_plugin]Archive read exception:boost::filesystem::remove: Access is denied [system:5]: "C:\Users\tmgxbs\AppData\Roaming\BambuStudio\plugins/BambuSource.dll"

from the log, it seems the dll is occupied by someone else
are you using multiple BambuStudio at the same time?
if yes, please exit from other BambuStudio before install the plugins.

Also you can check in the task manager to check whether there is another instance there, if yes, please kill that ones firstly

**Comment by bjornsyse** [comment]
No other instances running no. I double checked in the Task manager.

**Comment by bjornsyse** [comment]
I launched as administrator now, and the plugin installed. But when I launch as regular user after that, I still get an error it can not be installed.

**Comment by lanewei120** [comment]
could you give a snapshow of the directory "C:\Users\tmgxbs\AppData\Roaming\BambuStudio\plugins"
and you can attach the log this time here.

**Comment by bjornsyse** [comment]
Reporting that after another restart of the computer, I Can now start the program as regular user too, and the installation happened again in that session. 

Folder you mentioned has these files: 

`backup\
bambu_networking.dll
BambuSource.dll`

**Comment by lanewei120** [comment]
> Reporting that after another restart of the computer, I Can now start the program as regular user too, and the installation happened again in that session.
> 
> Folder you mentioned has these files:
> 
> `backup\` `bambu_networking.dll` `BambuSource.dll`

so could you upload the log here this time?

**Comment by bjornsyse** [comment]
Sorry, here comes. There were multiple but these are all from today. 
[log.zip](https://github.com/bambulab/BambuStudio/files/10965553/log.zip)

**Comment by lanewei120** [comment]
from log, it seems the plugins worked well

so it seems the application can work as normal now

do you have any other issues?

**Comment by bjornsyse** [comment]
Hi, no thank you for your troubleshooting - now it works. I'm behind so many firewalls/virus programs/endpoint protections and proxy's you'd never know where it might have failed. There is nothing I can do to turn them off unfortunately.

**Comment by bjornsyse** [comment]
So, had the same problem today when trying to install the 1.6.2.4. 

What finally worked, was:

1. after installation - start Bambu studio as administrator. Network plugin get's installed automatically. 
2. Copy `bambu_networking.dll` from `c:\Users\[MYADMINACCOUNT]\AppData\Roaming\BambuStudio\plugins\` to `c:\Users\[MYUSERACCOUNT]\AppData\Roaming\BambuStudio\plugins\`
3. Start bambu studio as regular user.

**Comment by lanewei120** [comment]
Glad to hear it, thanks for the information~

**Comment by lanewei120** [comment]
@Denislaaav please report a new issue, our QA will contact you there
