### ISSUE TITLE
libbambu_networking.so causes extreme slow startup because of split_lock errors on modern CPUs

### ISSUE THREAD

**Issue by seeraven** [bambulab/BambuStudio#8605]
### Bambu Studio Version

2.2.0.85 / 2.2.1.58 / 2.2.1.60 / 2.2.2 / 2.3.0 / 2.3.1.51

### Where is the application from?

Bambu Lab github releases

### OS version

Ubuntu 22.04 / Ubuntu 24.04

### Additional system information

CPU: 12th Gen Intel(R) Core(TM) i7-12700KF
Memory: 64GB
GPU: NVIDIA GeForce GTX 1060 6GB

### Printer

Bambu Lab A1

### Printer Firmware Version

01.07.00.00

### How to reproduce

1. Buy a computer with a recent Intel CPU.
2. Install Ubuntu 22.04 or 24.04.
3. Start BambuStudio and install the network plugin.
4. Stop BambuStudio.
5. Start BambuStudio again.
6. Wait about a minute or two until BambuStudio is ready
7. Look at the output of `sudo dmesg` to see the `x86/split lock detection` warnings that cause the slow down

You can also generate a `SIGBUS` that causes BambuStudio to not start at all:
1. Set the kernel option `split_lock_detect=fatal` and reboot.
2. Start BambuStudio.
3. On the console you will see the bus error caused by the split lock detection.

### Actual results

The application hangs during startup for about 25 seconds. Then the window is displayed. Then the application hangs again for about 10 to 20 seconds. When clicking on `Device` another hang is experienced.

When looking at the kernel messages (`sudo dmesg`) you will see the split lock detection that correspond to the hang:
```
[  367.383131] x86/split lock detection: #AC: bambustu_main/7299 took a split_lock trap at address: 0x70efbde2649f
[  373.309363] x86/split lock detection: #AC: bambustu_main/7405 took a split_lock trap at address: 0x70efbde2644f
[  444.387421] x86/split lock detection: #AC: bambustu_main/6922 took a split_lock trap at address: 0x70efbde26479
```

Correlating the addresses with the `/proc/<pid>/maps` output shows the addresses are within the `libbambu_networking.so` library:
```
70efbd800000-70efbdc66000 r-xp 00000000 fc:00 23762131                   /home/clemens/.config/BambuStudio/plugins/libbambu_networking.so
70efbdc66000-70efbdc67000 r-xp 00466000 fc:00 23762131                   /home/clemens/.config/BambuStudio/plugins/libbambu_networking.so
70efbdc67000-70efbe41f000 r-xp 00000000 00:00 0 
70efbe41f000-70efbe582000 r--p 00000000 00:00 0 
```

So the `libbambu_networking.so` uses a lock (presumably during the initialization of the variables) that is **not** properly aligned. This is detected by newer CPUs and trigger a CPU exception. The kernel in its default configuration (`split_lock_detect=warn`) warns, adds a delay and continues.

### Workaround

By disabling the split lock mitigation using the command
```
sudo sysctl -w kernel.split_lock_mitigate=0
```
and starting Bambu Studio again, the startup time is back to normal.

### Expected results

No delay is expected and no kernel warnings about the `split lock` are expected. This means the misaligned lock in the `libbambu_networking.so` file must be corrected. Disabling the split lock mitigation using the command `sudo sysctl -w kernel.split_lock_mitigate=0` can only be a temporary workaround as the split lock detection is there for a good reason: Using unaligned locks causes a full lock of the memory bus and impacts performance severely.

### Project file & Debug log uploads

Project File: [empty_project_for_split_lock_bug.zip](https://github.com/user-attachments/files/23259757/empty_project_for_split_lock_bug.zip)
Log File:  [log.zip](https://github.com/user-attachments/files/23259767/log.zip)
dmesg: [dmesg.zip](https://github.com/user-attachments/files/23259840/dmesg.zip)

### Checklist of files to include

- [x] Log file
- [x] Project file

**Comment by rene-rex** [comment]
I can confirm the mitigation works under openSUSE Tumbleweed with Bambu Studio version 2.3.0.70.
CPU: 12th Gen Intel® Core™ i5-12400F

**Comment by oodlexaps** [comment]
`sudo sysctl -w kernel.split_lock_mitigate=0` makes 2.3.0.70 hangs a *lot* less, but still hangs whereas 2.1.1.52 doesn't.

Xubuntu 25.04 on
Intel 13th Gen Core i5-13500 1 physical processor; 14 cores; 20 threads

If it helps: even after the first time through the tabs, it takes a few seconds to switch to the Device tab.

**Comment by kooscode** [comment]
I can confirm this is indeed a split_lock issue in `libbambu_networking.so`

I setup my kernel to segfault when encountering a split_lock instead of warn .. i.e added  `split_lock_detect=fatal` to grub..

I then compiled the latest tip of tree with Debug flags and ran Bambu Studio through GDB..

It was terminated by kernel with this message in GDB: 
```
Thread 1 "bambustu_main" received signal SIGBUS, Bus error.
0x00007fffc25a6b3e in ?? () from /home/xxxx/.config/BambuStudioInternal/plugins/libbambu_networking.so
```

DMESG also reported this Kernel error:
`[ 4390.970176] traps: bambustu_main[14534] trap alignment check ip:7300ee5a6b13 sp:7fff945879f7 error:0`

PLEASE FIX YOUR CODE!  

BambuStudio is rendered un-usable with latest Ubuntu 24.04 on my Intel i9-14900KF with 64GB RAM and RTX4090

**Comment by BrettRogersUK** [comment]
Looks like @MackBambu has been assigned to this one as well. I guess we can expect to see absolutely nothing from this person much like on the issue I raised (#8003 ). Assigned end of August and numerous people commenting about the same issue but alas nothing from @MackBambu.

**Comment by Epicguru** [comment]
Thanks for tracking down the issue. The app is currently unusable on Ubuntu because of this. It's disappointing to see a lack of action on Bambu's part.

**Comment by dbrannon79** [comment]
I believe I am also effected by this same issue.  I have been trying to figure out why the latest release of the appimage was constantly freezing and crashing.  In some instances my entire pc would lock up and would require a force power cycle to get thing going again.   

as a test I still had an older copy of the appimage  Bambu studio pr-6688 (ver 2.0.3.54) and it starts and works perfectly fine.

my system: Intel 12th gen I7-12700KF, AMD RX 6950 XT, Kubuntu 24.04, kde plasma 5.27.12.
Printer: H2D

searching and found this report.  ran the workaround in terminal listed above and re-launched the latest appimage.  seemed to be a little faster but is still a bit laggy.  no crashes or freezes thus far.    

Please look into this, without this workaround the latest version is almost un-usable, at times I have to force close the app and re-launch, about the third or fourth time re-launching it will finally stabilize enough to use the printer.

**Comment by p1h3** [comment]
I've had the same issue since v2.2.x.x.
I've tested it with v2.3.1 now (Bambu_Studio_ubuntu-24.04_PR-8583.AppImage ), but it's still crappy. It starts slowly and then has slow page changes, so I don't use it.

I'm currently using Bambu_Studio_ubuntu-24.04_PR-7292.AppImage, v2.1.1.52. It still works fine for now.

I tried this workaround (sudo sysctl -w kernel.split_lock_mitigate=0), it started a little faster, but still didn't run as smoothly as v2.1.1.52

I hope someone will fix this. Best wishes!

This machine also uses a new generation CPU: Intel Core Ultra 7 155U

Relevant machine details: [T14_system_info.txt](https://github.com/user-attachments/files/23430984/T14_system_info.txt)

**Comment by seeraven** [comment]
Unfortunately still no news, even after opening the support ticket on 2025-10-29. Last message was

> After investigation, we found that this issue involves Linux kernel-related logic. We will continue to investigate and optimize this situation in future versions.

Doesn't sound like the problem was understood (it's CPU related, not kernel related) nor that we can expect any progress soon. Nevertheless I have asked again for an update on this issue.

**Comment by dbrannon79** [comment]
It would be nice to hear something from the developers, at least a reassurance they are still actively looking at it.

I know it's not the best option, but if others open separate support requests showing the same terminal code allowing the app to function might get their attention.

Don't know what security risks we've all opened our CPU's to by using this workaround vs degraded functionality for other applications by using the workaround.

**Comment by BrettRogersUK** [comment]
> It would be nice to hear something from the developers, at least a reassurance they are still actively looking at it.
> 
> I know it's not the best option, but if others open separate support requests showing the same terminal code allowing the app to function might get their attention.
> 
> Don't know what security risks we've all opened our CPU's to by using this workaround vs degraded functionality for other applications by using the workaround.

You won't get a response. Ive had a ticket open for the same issue since end of August and still nothing from the developers.

**Comment by kooscode** [comment]
Best of it all is that it works 100% on ORCA Slicer nightly build using the Bambu Labs network plugin..

So maybe Bambu devs can go look  at how ORCA sliver devs fixed Bambu's code!

**Comment by oodlexaps** [comment]
> Best of it all is that it works 100% on ORCA Slicer nightly build using the Bambu Labs network plugin..
> 
> So maybe Bambu devs can go look at how ORCA sliver devs fixed Bambu's code!

Are you saying that on a computer where Bambu Studio has the problem, Orca Slicer does not?

If so that means we should be able to fix the Bambu Studio code.

**Comment by ismaia** [comment]
The app is unusable in Fedora 42/43. 
Without network plugin, it starts normally. After network plugin install, it freezes all the time

**Comment by kooscode** [comment]
> > Best of it all is that it works 100% on ORCA Slicer nightly build using the Bambu Labs network plugin..
> > So maybe Bambu devs can go look at how ORCA sliver devs fixed Bambu's code!
> 
> Are you saying that on a computer where Bambu Studio has the problem, Orca Slicer does not?
> 
> If so that means we should be able to fix the Bambu Studio code.

Correct..  I have both on my machine and nightly build ORCA works perfect..latest Bambu Studio hangs..

**Comment by seeraven** [comment]
OrcaSlicer uses the version 01.10.01.01 of the network plugin, although a flag is in the code to use 02.01.01.52 as an alternative (though you would need to build it yourself).

Porting the code back from OrcaSlicer to BambuStudio could be done of course, but I doubt that BambuLabs would approve and integrate such a pull request. So why not use Orca right away and drop BambuStudio?

**Comment by dbrannon79** [comment]
> OrcaSlicer uses the version 01.10.01.01 of the network plugin, although a flag is in the code to use 02.01.01.52 as an alternative (though you would need to build it yourself).
> 
> Porting the code back from OrcaSlicer to BambuStudio could be done of course, but I doubt that BambuLabs would approve and integrate such a pull request. So why not use Orca right away and drop BambuStudio?

My issue is they haven't yet gotten the H2D profile up and working on Orca yet that I'm aware of.  I was using Orca exclusively for my other printers until going off the deep end purchasing the H2D!

**Comment by seeraven** [comment]
Just in case some developer reads this next year or so, solely loading the library creates a ton of split_lock errors. Here is an example of the network plugin version 02.02.02.52:
```
sudo perf stat -e sq_misc.split_lock ./loadtest

 Performance counter stats for './loadtest':

             1.126      sq_misc.split_lock                                                    

       0,035698084 seconds time elapsed

       0,029688000 seconds user
       0,006142000 seconds sys
```
That are 1126 memory bus locks only for loading the library, not calling any function of it! 

Looking at the ELF file notes, I suspect the code "protector" VirBox that is used here is the source of all the split_locks. I see them for all 02.xx.xx.xx plugin versions, but not for 01.10.01.01.

**Comment by oodlexaps** [comment]
> OrcaSlicer uses the version 01.10.01.01 of the network plugin, although a flag is in the code to use 02.01.01.52 as an alternative (though you would need to build it yourself).
> 
> Porting the code back from OrcaSlicer to BambuStudio could be done of course, but I doubt that BambuLabs would approve and integrate such a pull request. So why not use Orca right away and drop BambuStudio?

I had convinced myself I wanted to stay with Bambu Studio to be able to us the Handy app, but maybe I don't need that.

I will consider using Orca slicer.  I just did a bunch of searching and it is still not clear to me what that means other than losing the connection to Handy.  

Are there any downsides to using version 01.10.01.01 instead of 02.01.01.52 ?

**Comment by kooscode** [comment]
> > OrcaSlicer uses the version 01.10.01.01 of the network plugin, although a flag is in the code to use 02.01.01.52 as an alternative (though you would need to build it yourself).
> > Porting the code back from OrcaSlicer to BambuStudio could be done of course, but I doubt that BambuLabs would approve and integrate such a pull request. So why not use Orca right away and drop BambuStudio?
> 
> I had convinced myself I wanted to stay with Bambu Studio to be able to us the Handy app, but maybe I don't need that.
> 
> I will consider using Orca slicer. I just did a bunch of searching and it is still not clear to me what that means other than losing the connection to Handy.
> 
> Are there any downsides to using version 01.10.01.01 instead of 02.01.01.52 ?

You don't lose anything. Orca integrates with Bambu Cloud and you login the same as with Bambu studio..

You can even run Bambu and Orca slicers on the same machine at same time.. Handy App works fine..

Only thing you don't have in Orca is Maker world browser, but you can use a standalone brother and just download the model manually..

**Comment by oodlexaps** [comment]
> You don't lose anything. Orca integrates with Bambu Cloud and you login the same as with Bambu studio..
> 
> You can even run Bambu and Orca slicers on the same machine at same time.. Handy App works fine..
> 
> Only thing you don't have in Orca is Maker world browser, but you can use a standalone brother and just download the model manually..

I keep reading that you have to switch to LAN mode or downgrade the P1S firmware to keep the ability of Orca to print directly to the printer.
I am going to give this a try as soon as I can and report back.
I always download models from a standalone browser anyway so losing that in the slicer doesn't bother me.

I apologize that these Orca questions are off topic to the bug, but I think for some of us this is going to be the bug "fix".

**Comment by dbrannon79** [comment]
> > You don't lose anything. Orca integrates with Bambu Cloud and you login the same as with Bambu studio..
> > You can even run Bambu and Orca slicers on the same machine at same time.. Handy App works fine..
> > Only thing you don't have in Orca is Maker world browser, but you can use a standalone brother and just download the model manually..
> 
> I keep reading that you have to switch to LAN mode or downgrade the P1S firmware to keep the ability of Orca to print directly to the printer. I am going to give this a try as soon as I can and report back. I always download models from a standalone browser anyway so losing that in the slicer doesn't bother me.
> 
> I apologize that these Orca questions are off topic to the bug, but I think for some of us this is going to be the bug "fix".

Yes as far as my experience has been, your are correct in having to put the printer in lan mode along with enabling developer mode on certain models for Orca to work.   

I have been reading and there seems to be a dev version of Orca available that has added support for the H2D, but the printer requires both options to be turned on for it to work.  I have not tried it myself yet. Debating on if I should just wait until a public beta or official release is done.  I have even been holding off on updating the H2D's firmware just in case Bambu blocks something.

I am sure if someone puts in a feature request, they could implement maker world along with the other major sites into the app like Thingiverse and Printable.  That shouldn't be too hard to do and allow downloading to open the project or STL directly onto the build plate.  I think that alone would be nice, even adding a bookmarking method to save models you want to go back to or keep.

The only issue I find on maker world is just about every model you find all use the default license that prevents us from making small modifications to suit our personal needs and saving them as a remix or even keeping on our own account as a private collection.  I think most folks don't realize that being it's the default license to select when uploading a model.

**Comment by kooscode** [comment]
Screenshot from my Orca Slicer on Ubuntu 24.04.. You simply download the nightly build "AppImage" or "Flatpak" installer...   zero compiling or dev stuff required... its just download and run..

<img width="480" height="475" alt="Image" src="https://github.com/user-attachments/assets/fb58e6bc-5102-4faf-8627-d3645a3c4a55" />

<img width="1572" height="796" alt="Image" src="https://github.com/user-attachments/assets/3cc345c9-7d5d-4180-9340-b3a701b94e6a" />

**Comment by oodlexaps** [comment]
I am on the latest firmware on my P1S.
Here's what I get:

<img width="570" height="385" alt="Image" src="https://github.com/user-attachments/assets/14e088bb-d4ae-479e-8c5b-69859f63c8be" />

<img width="1233" height="690" alt="Image" src="https://github.com/user-attachments/assets/2e256202-6d69-4052-bb26-21bbf6054369" />

<img width="779" height="65" alt="Image" src="https://github.com/user-attachments/assets/8a2c2320-bff2-41e7-9ecb-6cf3721ab819" />

**Comment by oodlexaps** [comment]
With the P1S in LAN only mode Orca connects properly.

**Comment by libussa** [comment]
would you guys mind taking this discussion elsewhere? I'm subscribed to get info about this bug and resolution, but this is turning into "how to run Orca slicer" and everyone gets notified 🙃 
This should be a good place https://github.com/OrcaSlicer/OrcaSlicer/discussions they also have a Discord

**Comment by kooscode** [comment]
> would you guys mind taking this discussion elsewhere? I'm subscribed to get info about this bug and resolution, but this is turning into "how to run Orca slicer" and everyone gets notified 🙃 This should be a good place https://github.com/OrcaSlicer/OrcaSlicer/discussions they also have a Discord

Feel free to unsubscribe from notifications...  

IMHO, Having a discussion about how Orca actually works, is very relevant, showing how the base of Bambu Studio (Orca) is working, might give Bambu a few hints as to where to go look to go fix it..

**Comment by Bambu-Pomfret** [comment]
Hi @seeraven,

Thanks for sharing your findings on this issue — this is incredibly useful! We totally get how frustrating it is when a technical roadblock comes up, especially when you’re looking to move forward quickly, and we’re fully committed to resolving this as efficiently as possible.

This is a complex technical item that requires detailed investigation to resolve effectively. We have already initiated the deep dive, using your insights to speed up our work.

We’ll provide updates as soon as we make meaningful progress. Feel free to reach out anytime with additional details or if you’d like an update on where things stand.

Thank you for your patience and understanding,

**Comment by BrettRogersUK** [comment]
> Hi [@seeraven](https://github.com/seeraven),
> 
> Thanks for sharing your findings on this issue — this is incredibly useful! We totally get how frustrating it is when a technical roadblock comes up, especially when you’re looking to move forward quickly, and we’re fully committed to resolving this as efficiently as possible.
> 
> This is a complex technical item that requires detailed investigation to resolve effectively. We have already initiated the deep dive, using your insights to speed up our work.
> 
> We’ll provide updates as soon as we make meaningful progress. Feel free to reach out anytime with additional details or if you’d like an update on where things stand.
> 
> Thank you for your patience and understanding,

We have been trying to get a response from someone for ages. I opened a issue #8003 back in August about this but nothing was done about it. 

Communication or lack therof is very poor indeed. We can't as users be used to fix your bugs for you. You need to sort that out yourself. When we do find a bug we raise an issue for you to fix it. 

This has been going on for so long now without any input from developers whatsoever. 

I guess all the talk about moving from Bambu Studio over to Orca Slicer as it worked without fault did pay off after all and wake these developers up.

**Comment by seeraven** [comment]
> Hi [@seeraven](https://github.com/seeraven),
> 
> Thanks for sharing your findings on this issue — this is incredibly useful! We totally get how frustrating it is when a technical roadblock comes up, especially when you’re looking to move forward quickly, and we’re fully committed to resolving this as efficiently as possible.
> 
> This is a complex technical item that requires detailed investigation to resolve effectively. We have already initiated the deep dive, using your insights to speed up our work.
> 
> We’ll provide updates as soon as we make meaningful progress. Feel free to reach out anytime with additional details or if you’d like an update on where things stand.
> 
> Thank you for your patience and understanding,

Good to hear from you @Bambu-Pomfret !

I suspect the main culprit is the VirBox Protector used to obfuscate the plugins. Even if you do not have a CPU throwing runtime exceptions you can use the `perf` method I mentioned [above](https://github.com/bambulab/BambuStudio/issues/8605#issuecomment-3543993403) to look for unaligned locking occurrences. Loading the plugin with `dlopen()` already triggers those.

Hope it helps and looking forward to hear from you soon!

**Comment by tomkroening** [comment]
Hi @Bambu-Pomfret  how are things proceeding with a fix? Is there anything more you need from the community to bring this to closure? I am picking up a P2S later this week and am looking forward to being able to run Bambu Studio from my Ubuntu PC. Thanks!

**Comment by tomkroening** [comment]
Hi @Bambu-Pomfret  and @MackBambu  following up on this. I'm happy to help if needed. Thanks.

**Comment by vmaksymiv** [comment]
I'm also running into this issue. @Bambu-Pomfret @MackBambu @walterwongbbl, I can confirm it happens on Ubuntu 25.04/Intel Core Ultra 7 155H as well.

**Comment by greve** [comment]
Same issue here. Fedora 43. Lenovo Thinkpad X1.

**Comment by MB911MB** [comment]
Same issue here. Linux Mint LMDE7
Lenovo Thinkpad
Intel© Core™ Ultra 7 155H × 16

What i tryed to test was to switch back to the old libbambu_networking.so (linux_02.00.03.55)
First start with the old network plugin normal fast, but with the first start, Bambu Studio will start the update of the network plugin automaticly and after update same issue.

2nd think i see with this bug is:
if i setup on the engine page the AMS Filament it will need very long most time i have to set it manually 3-4 times to a new value till it will set to the new value.

@MackBambu @Bambu-Pomfret @walterwongbbl  Is it possible to turn off the automatic nework plugin update as workaround till a fix will be delivered?

**Comment by fanjules** [comment]
I realise this is about linux but the problem is rife on Windows.  It's been there for months but seems much worse in recent updates.

bambu_networking.dll is the culprit, remove it and Bambu is like a rocket, but then you can't connect to your printer.

The devs don't realise that thousands of newbies coming to Bambu for the first time are being hit with an awful user experience. e.g.
https://forum.bambulab.com/t/constant-freezing-locking-up-in-device-section-on-windows/220131/39

If I use Bambu Connect, there is also some minor stutters and lock ups during startup, presumably as it's loading some networking library although I can't find bambu_networing.dll in it's list of files (maybe it gets it from somewhere else or the offending code is in the main executable).  So it's evidently part of the same bugged code.

I evaluate the CPU locks simply by trying to drag a window around the screen.  My machine has 24 cores.  If I load a very heavyweight application like CAD or a Jetbrains IDE, there is no stutter.  Yet little Bambu Connect (with no rendering and just printer status) will lock the whole OS and Bambu Studio is unusable.

**Comment by jaemzfleming** [comment]
Thanks for finding this Seeraven, I can confirm I'm seeing this as well, running ubuntu 24.04 and it's very aggravating.  Bambu Studio devs, fixing this should be top priority!

**Comment by walterwongbbl** [comment]
@greve @jaemzfleming @fanjules 
We sincerely apologize for the problem. We are currently working on a solution.

**Comment by BrettRogersUK** [comment]
has anybody got this problem. My flatpak install has automatically updated to version 2.5.0.66 on my Ubuntu Linux laptop and now the entire program is unusable. The previous version wouldn't sync my custom presets either. But this version, 2.5.0.66, is unusable. I cannot click on anything and I still have the FORCE QUIT or WAIT buttons when loading it. When I click on anything it take an absolute age to respond. Nothing to do with the laptop as I can use it perfectly when not using Bambu Studio. It's as though it is using all the CPU and RAM. It effectively renders my laptop unusable. 

I have loved Bambu studio up until this error (FORCE QUIT or WAIT) crept in at v2.2 and now it's become unusable. I do have a previous version as well that I downloaded as an appimage (v2.2.2.56) and this works as it should with no problems other than the FORCE QUIT or WAIT box.

EDIT: I removed the com.bambulab.BambuStudio folder from the .var/app/ folder on my laptop and restarted the v2.5.0.66 and it loaded up. I managed to get through the setup wizard and installed the network plugin and closed the application down. Upon restarting, I still get the FORCE QUIT or WAIT box but now the software is responsive again. However, like in the previous version there is an issue with the sync from the cloud server as it isn't pulling my process preset down. I saved my preset with my name on the end and it is not in the list. See attached images. When running v2.2.2.56 this preset comes down without issue and I can select it from the process preset list.

CPU: 12th Gen Intel i7-1255U

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/5c8610ef-83c1-46c0-8869-3743247f4ae5" />
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/23c6a57c-fbcf-4c9d-a996-84c4c85edc30" />

**Comment by BrettRogersUK** [comment]
> [@greve](https://github.com/greve) [@jaemzfleming](https://github.com/jaemzfleming) [@fanjules](https://github.com/fanjules) We sincerely apologize for the problem. We are currently working on a solution.

@walterwongbbl 

Whatever changes you're making to Bambu Studio are not making it better. If anything they are making it worse making the software unusable and in effect making it a very bad user experience for any users that are coming to Bambu Lab for the first time. Please sort it out! it is very frustrating!

**Comment by robertoswald** [comment]
Still the same issue with version 2.5.0.66 and installed network_plugin, unusable until
`sysctl kernel.split_lock_mitigate=0` . 
CPU:  13th Gen Intel(R) Core(TM) i7-13700H

Works flawless on: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz

**Comment by StefanKi** [comment]
I also have the problem.
"sysctl kernel.split_lock_mitigate=0" makes it way more usable, but then it uses 100% of one cpu. This makes my notebook quite loud.

**Comment by greathorse12** [comment]
I'm having this issue on an Intel 14900KS

**Comment by NxtGenCowboy** [comment]
Any update on the issue?   Lots of us with newer intel chipsets still can't use versions pass 2.3.1.51

**Comment by xplatinum** [comment]
The last good version for me is `v02.01.01.52`. It's also the last version to output this when launching from the terminal.

```
loading network module at /home/user/.config/BambuStudio/plugins/libbambu_networking.so
```

Versions that followed only output this:
```
after dlopen, network_module is 0x555eabcb0560
```

**Comment by xplatinum** [comment]
> `sudo sysctl -w kernel.split_lock_mitigate=0` makes 2.3.0.70 hangs a _lot_ less, but still hangs whereas 2.1.1.52 doesn't.

Same here. It helps but it still hangs occasionally.

i7-12700K

**Comment by xplatinum** [comment]
@walterwongbbl Do you have a ball park ETA on when we should be expecting a fix? Thanks.

**Comment by julrich1** [comment]
We really need an update on this. Bambu Studio is unusable and constantly locks up. We are going on 5 months now, when is the fix?

**Comment by sbrocket** [comment]
+1, I've got BambuStudio running inside a Linux Mint VM under Proxmox and any interaction with the network plugin causes extreme slowdowns. In my case it's the host (the hypervisor) that is doing the split lock mitigation, and I've confirmed using the steps from https://pve.proxmox.com/wiki/Split_lock_detection while interacting with Bambu Studio's network functions (like changing filament settings on a printer) that the issue is split locks triggering this mitigation.

Bambu folks, this is an issue in your closed source network plugin that you distribute as a binary, and as such there is absolutely nothing the community can do to further diagnose and fix it for you. You will need to fix whatever in that closed source library is performing misaligned memory accesses.

To copy from the wiki above for more background, "Starting with Linux kernel 5.19, every time a thread takes a split lock, the Linux kernel artificially slows down the thread by making it sleep for 10 milliseconds and synchronizing it with other threads taking split locks. This is controlled by the [split_lock_mitigate sysctl parameter](https://docs.kernel.org/6.2/admin-guide/sysctl/kernel.html#split-lock-mitigate-x86-only). See the related [LWN article](https://lwn.net/Articles/911219/) for more details. This is done to make denial-of-service attacks infeasible and keeping the offending thread from affecting the other running processes."

Users can disable the split lock mitigation as a workaround...but that means that these misaligned accesses are still slowing down other processes because the processor has to lock more than just a cache line to ensure consistency, and also opens them up to the DoS attacks from untrusted workloads that the mitigation was originally intended to make infeasible. So this really needs to be fixed in the plugin rather than just worked around. Based on the bpftrace test from the Proxmox wiki above, BambuStudio is performing *lots* of these misaligned accesses all at once, not just a few.

Perhaps you are building that closed source library using alignment settings or assumptions that are not true on the end machines where the library is actually run? Containerization and techniques like Flatpak/AppImage aren't going to save you on this particular problem. None of those layers, nor even the KVM layer in the case of VMs, can fix this kind of memory access alignment issue on behalf of the end software. You probably need to identify which operations are misaligned and then align them in some conservative way that will end up aligned across a variety of CPU platforms.

**Comment by cronzevid** [comment]
@rouyuanzi-bambu @MackBambu @walterwongbbl @Bambu-Pomfret

This issue (#8003) has been open since August. It is now March. Seven months of complete silence on a critical, breaking issue is unacceptable.

Not only did the community identify this bug months ago, but also provided the exact root cause and actionable fixes. Despite this, you have pushed at least four major releases - adding new features - while completely ignoring a glaring flaw in your proprietary code.

BambuStudio is not an optional, third-party addon, it is a core component of the hardware ecosystem we paid for. Customers purchase your flagship products, like the H2-series, with the expectation that they "just work." Currently, they do not. Using an alternative slicer is not a viable workaround for your flagship line.

The only reason my H2D is still functional is due to the unpaid efforts of open-source developers. Thanks to OrcaSlicer, I can roll back to a stable version of your closed-source network plugin. However, achieving this required the technical background to manually merge and build a specific PR ([11645](https://github.com/OrcaSlicer/OrcaSlicer/pull/11645)), which is currenty merged into main branch. Your average customer cannot and should not have to do this.

You are shipping proprietary code that breaks your hardware and leaving the open-source community to clean up the mess.
When can we expect a formal response and a merged fix for this issue?

**Comment by sbrocket** [comment]
> I accidentally let my Windows version download the networking module and it now seems to be partially fixed. It's still stutters the whole OS when I goto print but now it seems more manageable and doesn't lock for several minutes at startup. This is the first time I've actually managed to print from Studio in months, although I still might print via Bambu Connect due to the stutter when trying to print. I don't know about the Linux version as I uninstalled Studio in Linux a while ago.

Unrelated issue if not on Linux, please don’t just off-topic post to random other issues. This is also much more of a nebulous customer support “my thing doesn’t work” question than some clear and actionable symptom, so you’re probably unlikely to find help on Github.

**Comment by Epicguru** [comment]
It's been almost 6 months of your software being non-functional for one of the 'supported' operating systems. The issue has been identified, it is trivial to replicate. What fixes or changes are taking priority over this?

**Comment by xplatinum** [comment]
@MackBambu @walterwongbbl  @Bambu-Pomfret 
I can't believe it's taking them so freaking long to simply ACKNOWLEDGE the issue here and reassure the community that they are working on it. Even after pinging the devs multiple times. I'm beyond disappointed. This is very poor customer service for such an expensive device.

**Comment by Bambu-Pomfret** [comment]
Hi everyone,

First of all, we sincerely apologize for the extended delay in resolving this issue, and for the frustration it has caused — especially for those of you on Linux with recent Intel CPUs who have been unable to use Bambu Studio normally for months. We understand how unacceptable this experience has been, and we take full responsibility.

We have spent considerable time investigating the root cause of this problem. After thorough analysis, we have confirmed that the split lock events originate not from our networking plugin source code itself, but from a third-party binary tool applied.

We are currently evaluating alternative approaches to our pipeline. However, since this involves changes to our build and release infrastructure — including security validation and cross-platform regression testing — it requires a careful transition period to ensure we do not introduce new issues.

Again, we apologize for the long wait. We appreciate the detailed technical analysis many of you contributed to this issue — particularly the perf measurements, GDB traces, and the version comparisons — which were invaluable in helping us pinpoint the cause.

**Comment by ClusterM** [comment]
```
sudo sysctl -w kernel.split_lock_mitigate=0
```
Workaround didn't work for me. So... What should I do? I bought a 3D printer for $1000 and can't use it without Windows PC?

**Comment by robertoswald** [comment]
Running `sudo sysctl kernel.split_lock_mitigate=0` before launching BambuStudio should make it much more usable, even it is not running perfectly afterwards it is at least usable.

**Comment by sbrocket** [comment]
“Usable” is extremely relative here. Disabling the split lock mitigation/penalty does seem to improve things, but it still takes literal, no exaggeration minutes to complete simple operations like change an AMS filament. Enough that I’ll go find my phone and open Handy to change settings after loading new filaments even if I’m already working in Bambu Studio, which is unacceptable.

It’s not even just when using non-Bambu filaments either…just yesterday I swapped in a couple spools of Bambu PLA Metal in the middle of another print, and needed to use the reread/refresh button on those slots after the print finished because the AMS didn’t automatically read them for some reason. Studio was far too slow and I had to go find my phone and use Handy.

Other operations, like first opening the Printer menu, thankfully don’t take minutes but are still painfully slow…10s of seconds. I would not call any of that acceptable levels of usable.

**Comment by seeraven** [comment]
> “Usable” is extremely relative here. Disabling the split lock mitigation/penalty does seem to improve things, but it still takes literal, no exaggeration minutes to complete simple operations like change an AMS filament. Enough that I’ll go find my phone and open Handy to change settings after loading new filaments even if I’m already working in Bambu Studio, which is unacceptable.

Unfortunately, we have two players in this game: the split locks which degrade performance and the mitigation of the kernel to make users aware of those split locks. Since the split locks are coded into the "secured" network plugin, there is nothing we can do to prevent them. However, we can disable the mitigation by the kernel using `sudo sysctl kernel.split_lock_mitigate=0` which disables those random sleeps when a split lock occurs.

But after disabling the split lock mitigation, we still get the effect of the split locks. And you clearly see why split locks are such a bad thing, because the performance of BambuStudio is very poor on modern processors.

So I hope the tool used to obfuscate the binary code of the network plugin is fixed soon to finally end this misery.

**Comment by sbrocket** [comment]
Yeah I understand the situation. I just wanted to re-highlight the effects especially now that we have someone from Bambu watching, and to ensure someone doesn't end up mistakenly thinking publishing instructions to disable that flag is a "fix". It's not; it's a partial workaround, but only partial and performance is still poor.

**Comment by ClusterM** [comment]
It turns out that Bambu Lab printers can stream video as a regular RTSP feed without any extra software. That at least solves the problem of viewing the camera stream.

**Comment by Timefactor** [comment]
Adding my name to this issue. No issues seen on my AMD system. Only my intel systems are experiencing the problerm.

**Comment by ClusterM** [comment]
I made my own solution: https://github.com/ClusterM/open-bambu-networking
I'd be happy if you test it on different printers.

**Comment by tomkroening** [comment]
> I made my own solution: https://github.com/ClusterM/open-bambu-networking I'd be happy if you test it on different printers.

Wow.... I am very impressed. I don't know how you have that kind of time to spend. I am just using a separate Windows PC for Bambu Studio until Bambu Lab fixes the bug. It's annoying for sure but I only use the slicer for a few minutes compared to hours with CAD.

**Comment by Swoy** [comment]
@Bambu-Pomfret I'm running on AMD hardware and the issue is exactly the same here, this is not Intel-specific. 8–9 months to fix something so trivial is wildly unacceptable and very disrespectful. Stop maintaining that this is about it being "security related". Be honest that this is about maintaining your walled garden. The community will eventually figure out how to circumvent all of this, and take back all the stuff you just took from us. I get that you want to make money. So does Prusa and they still give everything back to the community! Make money from quality and pride, not lock-ins and bullish strategies.

 Same story with the RFID lock-ins: your system can't even read your own chips reliably. Adopt the industry-standard OpenTag3D and be the good guys for once. If your filament really is the best, there's no need for a locked system, people will buy it for the quality, not because you soft-force it on them.

**Comment by Bambu-Pomfret** [comment]
Hi everyone,

First of all, we sincerely apologize for the long delay caused by this networking issue.
We greatly appreciate your patience and continued support.

This issue has been prioritized and expedited internally, and we have directly replaced the third-party tool in the pipeline to fix it.

The updated networking plugin will be automatically downloaded when you launch the latest pre-release version of Bambu Studio (2.6.1 Public Beta).

Please update to Bambu Studio 2.6.1 Public Beta and launch the software, then verify if the issue has been resolved on your end.

The full pipeline investigation turned out to be far more complex and time-consuming than expected, and we truly appreciate your understanding all along.

Thank you again for your valuable feedback and support!

**Comment by Swoy** [comment]
> I made my own solution: https://github.com/ClusterM/open-bambu-networking I'd be happy if you test it on different printers.

This is amazing work! I've worked on tuning the video stream in orca for some time and with this I now have crisp and realtime video in the software at last! I'm currently looking into BamBuddy which has loads of cool features.

**Comment by seeraven** [comment]
> Hi everyone,
> 
> First of all, we sincerely apologize for the long delay caused by this networking issue. We greatly appreciate your patience and continued support.
> 
> This issue has been prioritized and expedited internally, and we have directly replaced the third-party tool in the pipeline to fix it.
> 
> The updated networking plugin will be automatically downloaded when you launch the latest pre-release version of Bambu Studio (2.6.1 Public Beta).
> 
> Please update to Bambu Studio 2.6.1 Public Beta and launch the software, then verify if the issue has been resolved on your end.
> 
> The full pipeline investigation turned out to be far more complex and time-consuming than expected, and we truly appreciate your understanding all along.
> 
> Thank you again for your valuable feedback and support!

Thanks @Bambu-Pomfret for this update! It's good to hear that the problem is investigated further.

I've installed BambuStudio 2.6.1 Public Beta on my Ubuntu 22.04.5 LTS workstation with an 12th Gen Intel(R) Core(TM) i7-12700KF. However, it looks like the problem is unfortunately **not completely solved yet**. Looking at the `dmesg` output (with disabled `split_lock_detect=off` workaround) I see the following split lock detections:
```
[   41.354681] x86/split lock detection: #AC: bambustu_main/5143 took a split_lock trap at address: 0x70e7b137b223
[   43.876423] x86/split lock detection: #AC: bambustu_main/5212 took a split_lock trap at address: 0x70e7b0e40f66
[   46.808944] x86/split lock detection: #AC: bambustu_main/5476 took a split_lock trap at address: 0x70e7b120469e
[   47.495553] x86/split lock detection: #AC: bambustu_main/5511 took a split_lock trap at address: 0x70e7b0f5ea6e
[   48.506734] x86/split lock detection: #AC: bambustu_main/5520 took a split_lock trap at address: 0x70e7b120469e
[   48.957306] x86/split lock detection: #AC: bambustu_main/5469 took a split_lock trap at address: 0x70e7b0f38450
```
My subjective feeling is however, that the startup is faster.

**Comment by subnivean** [comment]
The AppImage is working great for me - Pop_OS (Ubuntu 24.04) on a System76 Adder WS w/13th Gen Intel(R) Core(TM) i9-13900HX (definitely *wasn't* before). It's on par now with another setup running on a Windows laptop. Thanks!

**Comment by kooscode** [comment]
This last update TOTALLY fixed everythign for me on Uvuntu 24.04 and Intel i9-14900K 

THANK YOU!!!!!

**Comment by jvoss117-2** [comment]
> Please update to Bambu Studio 2.6.1 Public Beta and launch the software, then verify if the issue has been resolved on your end.
> 

@Bambu-Pomfret I can hardly believe it, but everything seems to be working great now after updating to 2.6.1 Beta. I'm running the AppImage on Ubuntu 24.04.3 LTS with an Intel® Core Ultra 5 125H CPU.

Thank you for finally providing this fix!

**Comment by rene-rex** [comment]
Fixed in BambuStudio_ubuntu24.04-v02.06.01.55-20260429100944.AppImage running on openSUSE Tumbleweed.

**Comment by BrettRogersUK** [comment]
Hi, can confirm that is fixed in BambuStudio_ubuntu24.04-v02.06.01.55-20260429100944.AppImage and runs perfectly on Ubuntu 24.04.4 running on 12th Gen Intel i7-1255U, Intel Alder Lake-UP3 GT2 [Iris Xe Graphics], Kernel: 6.17.0-22-generic.

Also noted in issue https://github.com/bambulab/BambuStudio/issues/8003.

**Comment by ClusterM** [comment]
Still impossible to use when internet connection is down. Version 2.6.1.55.

<img width="1395" height="957" alt="Image" src="https://github.com/user-attachments/assets/45f85a1e-0a7a-44a4-ae51-802a1fdb40f9" />

And yes, still the same problem:
```
[255991.708392] x86/split lock detection: #AC: bambustu_main/414842 took a split_lock trap at address: 0x707e49b7b223                                                                                
[255995.269006] x86/split lock detection: #AC: bambustu_main/414949 took a split_lock trap at address: 0x707e49738450
[255995.270617] x86/split lock detection: #AC: bambustu_main/414974 took a split_lock trap at address: 0x707e49640f66
[255995.598444] x86/split lock detection: #AC: bambustu_main/414980 took a split_lock trap at address: 0x707e49a0469e
[256000.423885] x86/split lock detection: #AC: bambustu_main/415221 took a split_lock trap at address: 0x707e4975ea6e 
```

**Comment by sbrocket** [comment]
Confirmed that the 2.6.1 beta AppImage's performance is way better in the ways I use it, but it'd be great if the other user reports of split locks can be tracked down too. Or even better, checked for as part of an automated test, assuming y'all have other test automation already, to ensure this doesn't incidentally reoccur. Especially if these can be detected statically from the binary, but I'm not sure that they can be.

And fingers crossed for a quick full release since the flatpak Bambu Studio releases don't have a beta channel!

**Comment by cronzevid** [comment]
@Bambu-Pomfret
>We are currently evaluating alternative approaches to our pipeline.

For future reference, I would gladly offer my DevOps consulting services so your pipeline doesn't take half a year to deploy a critical fix.

Thank you anyway, app works fine now.

UPD: Yeah, I guess I am rescinding my offer after [this](https://blog.bambulab.com/setting-the-record-straight-on-cloud-access-and-community/) post. You obviously have no idea what opensource is and how it works (and that BambuStudio is just a poor fork), nor you have any respect to contributors.

**Comment by RayRayBornAgain** [comment]
Confirming this is still an issue as of Bambu Studio (Flatpak install) on Linux Mint.

Ran into repeated full UI freezes while working in the Prepare/Preview view (not just on startup or Device tab clicks). Confirmed via `top` that the process was alive but idle (~1% CPU, sleeping state) during the freeze — not a heavy compute/slicing operation, just hung.

dmesg output:
```
[ 76.766255] x86/split lock detection: #AC: bambustu_main/2333 took a split_lock trap at address: 0x741c738a0258
[ 82.271992] x86/split lock detection: #AC: bambustu_main/2645 took a split_lock trap at address: 0x741c72a62176
[ 83.253281] x86/split lock detection: #AC: bambustu_main/2681 took a split_lock trap at address: 0x741c72a889b9
[ 83.832638] x86/split lock detection: #AC: bambustu_main/2724 took a split_lock trap at address: 0x741c72a6b3ff
[ 84.238658] x86/split lock detection: #AC: bambustu_main/2720 took a split_lock trap at address: 0x741c72a62176
[ 84.833665] x86/split lock detection: #AC: bambustu_main/2758 took a split_lock trap at address: 0x741c72a62176
[ 85.521833] x86/split lock detection: #AC: bambustu_main/2447 took a split_lock trap at address: 0x741c72a62176
```

7 traps across different PIDs within a ~9 second window during normal use (not LAN-only mode, cloud features enabled).

Tried `sudo sysctl kernel.split_lock_mitigate=0` as a workaround — this reduces the per-trap performance penalty but does not stop the traps from occurring. Freezes are shorter but still present.

System info:
- OS: Linux Mint (Cinnamon)
- Install method: Flatpak (com.bambulab.BambuStudio)
- Not using LAN-only mode

Would be great to see this addressed upstream given how long it's been open — the unaligned atomic in the network plugin seems to be the root cause per the discussion here and in the open-bambu-networking project notes.
