### ISSUE TITLE
A lot of previous working filaments are now shown as unsupported in newest Bambu Studio update.

### ISSUE THREAD

**Issue by e30Birdy** [bambulab/BambuStudio#8855]
### Bambu Studio Version

2.4.0.70

### Where is the application from?

Bambu Lab Official website

### OS version

WIndows 11 25h2

### Additional system information

7950X3D
32gb
4080 Super

### Printer

P1S

### Printer Firmware Version

01.08.01.00

### How to reproduce

Open Bambu Studio. 
Go to Project FIlaments and swap filaments
A lot of previous working filaments are now shown as unsupported

### Actual results

A lot of previous working filaments are now shown as unsupported

### Expected results

All my filaments to show up as they were all created with a P1S printer being the only printer I installed in my slicer.

I opened Orca Slicer and all of the filaments show up there correctly.  I have also gone ahead and checked the dependencies tab in Orca since Bambu doesnt have that and they are all marked correct to worth with P1S and 0,4mm nozzle.

To test I installed the X1C as  printer I own and the profiles not working with the p1s show up there. I do not know if all do but most of them but then the P1S profiles are now unsupported.

I just did a big 12 hour print yesterday with the previous version of the software and no issues at all, all filaments worked fine.

### Project file & Debug log uploads

[debug_network_Wed_Nov_19_22_53_17.log.zip](https://github.com/user-attachments/files/23638584/debug_network_Wed_Nov_19_22_53_17.log.zip)

### Checklist of files to include

- [x] Log file
- [ ] Project file

**Comment by Jack-Edwards** [comment]
Also experiencing this issue with all of the Bambu PLA Matte and Bambu PLA Basic profiles I created.  Bambu PLA Glow, Generic PLA, and Overture presets are all fine.

These presets contained flow rate calibrations for all of my spools.  Please provide a remedy.

**Bambu Studio Version**

2.4.0.70

**Where is the application from?**

Flathub

**OS version**

Fedora 43

**Printer**

P1S

**Comment by Jack-Edwards** [comment]
Downgrading to the 2.3.1 public release restores the user presets.

`sudo flatpak update --commit=a2075c9d23fde2d133b2d2ac99f10ea3d409803423c205c2d1dd7121e7cb860f com.bambulab.BambuStudio`

**Comment by raykonator** [comment]
same here, and a message at every start, that the config is broken. 

fully uninstalled, new installation, now it works again, but at **_every_** start it starts the setup-agent. and a login is impossible.

how can i downgrade to 2.3.1?

**Comment by Chewieez** [comment]
I hit this same issue. 

I have a P1S and I found that all my unsupported filament presets inherited from an X1C preset that apparently no longer existed or wasn't mapped to the P1S. In my case it was usually from "Bambu PLA Basic @BBL X1C"

I fixed my presets by manually opening each .json file and changing the inherited file to "Bambu PLA Basic @BBL P1S 0.4 nozzle". 

I'm glad to see I wasn't crazy. I searched online for other people having the issue but didn't find anything.

**Comment by wtji-bbl** [comment]
Hello @e30Birdy , thanks for letting us know. Could you try to open filament settings (the gear icon on the top-right of the Project Filaments bar), make sure the Bambu P1S printer is checked on the left scroll bar, and click confirm. Is the problem still showing?

**Comment by WolfmoonCT** [comment]
I had the same issue.  I could not find the json file to change like Chewieez did, but running the v2.32.1.51 installer fixed the issue for now.

**Comment by e30Birdy** [comment]
> I had the same issue.  I could not find the json file to change like Chewieez did, but running the v2.32.1.51 installer fixed the issue for now.

It's in user > app data > roaming> bambu studio

**Comment by e30Birdy** [comment]
> Hello [@e30Birdy](https://github.com/e30Birdy) , thanks for letting us know. Could you try to open filament settings (the gear icon on the top-right of the Project Filaments bar), make sure the Bambu P1S printer is checked on the left scroll bar, and click confirm. Is the problem still showing?

<img width="623" height="427" alt="Image" src="https://github.com/user-attachments/assets/c26915cd-18e5-474d-98e5-54e520990f86" />

<img width="805" height="651" alt="Image" src="https://github.com/user-attachments/assets/9f591060-a21d-478f-901e-b3864650f905" />

Yep because it is the only printer I own from Bambu. Like I said they all worked fine with the prvious software version, they all work fine in orca and broke after the update to this new version. I know all my 0.6mm stuff won't work and do not know why some are called X1C as I have never had that printer installed. It started calling some profiles X1C when I updated my nozzle to hardened back in the day and I never manually renamed them.

**Comment by Mujin-code** [comment]
Hello, we attempted to reproduce the issue but were unable to do so. Could you please provide us with your preset file? In the user directory of the configuration folder, provide a preset that displays unsupported settings to help us locate the issue. We apologize for any inconvenience caused。

<img width="1283" height="753" alt="Image" src="https://github.com/user-attachments/assets/b3d6a3c0-5fba-4f53-af6d-b3589cbb7491" />

**Comment by Jack-Edwards** [comment]
Here is one of mine that was unsupported after the update.  I notice in the JSON the profile inherits from BBL X1C, a printer I don't have and don't have selected in Studio.  Is that the problem?

[Bambu PLA Matte - Calibrated.zip](https://github.com/user-attachments/files/23666872/Bambu.PLA.Matte.-.Calibrated.zip)

**Comment by Mujin-code** [comment]
Hello, it is normal to have X1C presets because the software has some system presets that will not affect your use. We will analyze the cause of the problem as soon as possible. Thank you for your understanding

**Comment by samanthariley2018-star** [comment]
Thank you for above. since updating the other day to 2.04... every print has failed no matter what PLA I use, it rips up the first few layers every time. I have deleted and re-installed 2.03.1 and about to try again. Clearly the PLA pre-sets in 2.4 need redoing (I use a P1S 0.4 nozzle)

**Comment by Mujin-code** [comment]
Hello, can you provide us with the sliced file of the model that failed to print for you? Files with the suffix gcode.3mf

**Comment by WolfmoonCT** [comment]
Here are mine. All of these are showing as unsupported at least on the P1..  I did not try any custom on the A1, as it is currently printing using the standard PEI plate and I did not need a custom for it. 

[Custom unsupported profiles.zip](https://github.com/user-attachments/files/23675803/Custom.unsupported.profiles.zip)

**Comment by kgregg384** [comment]
Same issue here.  I save a filament as a custom project level and the next time i open studio, it shows up under unsupported and i can't assign it.

**Comment by 3vi1** [comment]
I had the same problem, and fixed it in a manner similar to what Chewieez did.  The only difference was that I changed mine to inherit from the Generic PLA profiles.

On Linux, the files are in:  ~/.config/BambuStudioInternal/user/{your user number here}/filament/

**Comment by s-pankhurst** [comment]
I have the same issue with custom filament profiles showing as unsupported and cannot be selected.  I've rolled back to v2.03.01.51 which fixed it.

**Comment by nortagawa** [comment]
I'm experiencing the same problem on Bambu Studio 2.4.0:

- macOS 26.1
- Bambu X1 Carbon

My Fiberon PETG "system filament" profiles, which worked in 2.3.1, are now showing as "unsupported."  Rolling back to 2.3.1, then syncing filaments, restored their profiles.

**Comment by wwwabbit** [comment]
Same issue for me, multiple custom filament profiles are showing as unsupported.

**Comment by Skyeagle4** [comment]
I'm having this same issue right now.

**Operating System:**
• Windows 11 Pro
• Version: 25H2

**Bambu Studio version:**
• 2.4.0.70

**Printer:**
• Bambu Lab P1S
• Version: 01.09.00.00
• Auxiliary Devices:
- AMS Hub:
> Version: 00.00.00.43
- AMS:
> Version: 00.01.06.62

I don't know if it's related, but the SD card that the printer came with also randomly died inside the printer. I've possibly removed the thing once a year ago or more, I can't remember, but for some reason it said it was "Physically Damaged" and had to be replaced. 

<img width="887" height="1379" alt="Image" src="https://github.com/user-attachments/assets/76e2a526-f4ed-44e6-a5da-850aa11bddab" />
<img width="554" height="1379" alt="Image" src="https://github.com/user-attachments/assets/e34ca582-dac5-4056-8ae1-e514e17618f1" />

**Comment by Skyeagle4** [comment]
#

> I hit this same issue.
> 
> I have a P1S and I found that all my unsupported filament presets inherited from an X1C preset that apparently no longer existed or wasn't mapped to the P1S. In my case it was usually from "Bambu PLA Basic [@bbl](https://github.com/bbl) X1C"
> 
> I fixed my presets by manually opening each .json file and changing the inherited file to "Bambu PLA Basic [@bbl](https://github.com/bbl) P1S 0.4 nozzle".
> 
> I'm glad to see I wasn't crazy. I searched online for other people having the issue but didn't find anything.

@Chewieez Got it right with this solution, it worked perfectly. Slightly tedious, but it worked on my Windows 11 machine.

**Comment by RubAnADUB** [comment]
<img width="364" height="386" alt="Image" src="https://github.com/user-attachments/assets/79099d34-6892-4f11-895c-cb3d2d9e27d1" />
This is what I get for updating. =( 

HEY POS BAMBU LABS - updated firmware and bambu studio settings and now my AMS doesnt allow POLYTERRA or ESUN to be in the ams. Now my prints are SHEEEEEEET  because the printer filament settings are not how they were. STOP being a POS company and fix this ASAP.

**Comment by Mujin-code** [comment]
@RubAnADUB Hello, we are working on resolving this issue. Thank you for your understanding 
You can temporarily use the above method to solve your problem. We apologize for any inconvenience caused！

**Comment by jimisola** [comment]
I seem to have the same issue. I only see some Bambu Lab and Generic filaments even though I selected more filaments.
Tried on Windows, Linux, Android and the machine itself.

<img width="529" height="520" alt="Image" src="https://github.com/user-attachments/assets/b8923410-1946-4679-8f7f-70b8e8a19c67" />

**Comment by RubAnADUB** [comment]
so whens the fix?

**Comment by nocluewhatido** [comment]
Same Issue here using any Esuns config which where previously possible to use in Bambu Studio.

**Comment by shubhankartrivedi** [comment]
getting same issue with esun configs

**Comment by VArterJr** [comment]
Same. All my eSUNs aren't working on the P2S. They import (process and filament) but can't be used. I tried using the Bambu PLA-CF setting, but I start getting air prints. Would really like this working.

**Comment by nocluewhatido** [comment]
> Same. All my eSUNs aren't working on the P2S. They import (process and filament) but can't be used. I tried using the Bambu PLA-CF setting, but I start getting air prints. Would really like this working.

I think the P2S is not supported with eSUN settings for now.

**Comment by aimbdd** [comment]
It's march.,... any update on fixing this? still have this issue on 2.5.0.66

**Comment by RobSGW** [comment]
I cant believe this isn't fixed yet, I waited a couple months to finally update studio thinking surely this will be fixed, but nope. None of my custom P1S profiles are "supported" because they were created with X1C data as it always did. I've never owned an X1C. Now I have to go through each .json file and make the change, which is really annoying. Wont be updating again until this is resolved.

**Comment by RobSGW** [comment]
And here's the issue: Any custom filament profile that was created off of a base Bambu filament profile for the longest time used the X1C metadata, regardless if you were on a P1S or X1C. Now, because that profile is inherited from the X1C, studio does not recognize it as compatible with the P1S. The fix is easy but a bit time consuming depending on how many profiles you had. You have to go the the .json file in users/appdata/bambustudio/user/xxxxx/filament, open each .json file, and do the follwing:

Find this text string ---> **"inherits": "Bambu PLA Silk @BBL X1C**
And change it to this ---> **"inherits": "Bambu PLA Silk @BBL P1S 0.4 nozzle"**

Then save the file, restart studio and your profiles are back. I know this has been said before, but I figured the more places it's posted, the more people it will help.

**Comment by Lucas42hs** [comment]
Same problem here, not solved yet
Suddenly presets which worked yesterday, today arent compatible anymore

**Comment by 3dPrinter-man** [comment]
I have the same problem. Trying to add Generic PLA Silk (It actually is Elegoo PLA Silk but Bambu pretends Elegoo doesn't exist...) but it shows as Unsupported, A royal PITA!

**Comment by pozdrowiony** [comment]
Same issue here. I've had heart attack when realized dozens of hours spent on profile tuning might be lost. @RobSGW advice worked as workaround.

**Comment by soramis-eldon** [comment]
Yep. All my calibrated filaments from before I derived from generic stock profiles are "Unsupported" now as well. You broke a major part of the software for many users and you did nothing about it for half a year. Please check what you did. Please offer an "upgrade your filament settings" or whatever is necessary dialogue to fix this.

**Comment by prentice78** [comment]
This is STILL an issue? I just lost all my custom filaments that i dialed in.  I upgraded to the latest BS version.
This is insanely frustrating.

**Comment by nachimir** [comment]
Also having this problem, and the .json inheritance workaround wasn't solving it. Extensively editing the .json for one affected custom filament does seems to have resolved it for all affected ones though (steps below).

Bambu Lab A1, running latest firmware. MacOS Sequoia. I haven't changed printer or used Bambu Studio with any others; it's been the same printer throughout.

Have tried:

- Closing Bambu Studio, editing .json file inheritances of problematic custom filaments to other filaments that do work. Result: filament presets remain in "Unsupported" part of menu.
- Above steps, plus deleting corresponding .info file, causing the file to be regenerated next time I open Bambu Studio. No change to results.
- Making new custom filament preset from scratch in Bambu Studio, with settings to match old one. When saved, BS immediately places the new filament preset in "Unsupported" section of filaments menu.
- Editing non-working filament profile in text editor, side by side with one that does work, to remove extra parameters that don't seem to appear in working custom profiles (approx 180 extra lines). Save file, delete .info file. Result: On next load, Bambu Studio deletes edited file, reverts to 400 line version of file, custom filament remains in "Unsupported".

- EDIT: Exited Bambu Studio, repeated above edits to .json, set file to read only, reloaded Bambu Studio. Error message on startup. All filaments including Bambu's now in "Unsupported", but this time because Bambu is showing no printer selected. Close software, change file back to writable, reload Bambu Studio, select my A1. Result:

All previously inaccessible filament profiles now seem to be restored and usable. Bambu presets are back in place where they should be. The small number of custom filament presets that were previously unaffected by this issue are now listed as "Unsupported", but I can live with that.

This makes very little sense and has been incredibly frustrating. My presets for eSun, 3DQF, Jamghe, Deeplee, Elegoo, Eryone and SunLu all became inaccessible. The .json files were still there, I could read the settings, but for the past few months Bambu Studio was preventing me from using or even reimplementing ~18 months of discoveries and calibration. This meant I couldn't print well with certain third-party filaments that I'd optimised prints and processes for.
